# Generated by Django 5.2.5 on 2025-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='category',
            field=models.CharField(choices=[('plumber', 'plumber'), ('electrician', 'electrician'), ('painter', 'painter'), ('carpenter', 'carpenter'), ('other', 'other')], max_length=50),
        ),
    ]
